# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_longBayes_rcpparma_hello_world', PACKAGE = 'longBayes')
}

rcpparma_outerproduct <- function(x) {
    .Call('_longBayes_rcpparma_outerproduct', PACKAGE = 'longBayes', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_longBayes_rcpparma_innerproduct', PACKAGE = 'longBayes', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_longBayes_rcpparma_bothproducts', PACKAGE = 'longBayes', x)
}

bases <- function(J = 6L) {
    .Call('_longBayes_bases', PACKAGE = 'longBayes', J)
}

pg <- function(ts) {
    .Call('_longBayes_pg', PACKAGE = 'longBayes', ts)
}

lpg <- function(ts) {
    .Call('_longBayes_lpg', PACKAGE = 'longBayes', ts)
}

nsp <- function(spec, TR = 3.0) {
    .Call('_longBayes_nsp', PACKAGE = 'longBayes', spec, TR)
}

atsm <- function(pgram) {
    .Call('_longBayes_atsm', PACKAGE = 'longBayes', pgram)
}

mcmc <- function(y, eta, q, leps = 0.065, L = 15L, lepsrho = 0.13, Lrho = 10L, niter = 2e4L, Ltau = 1000, siga = 1000, sigmu = 1000) {
    .Call('_longBayes_mcmc', PACKAGE = 'longBayes', y, eta, q, leps, L, lepsrho, Lrho, niter, Ltau, siga, sigmu)
}

q_lspec <- function(q, J = 6L) {
    .Call('_longBayes_q_lspec', PACKAGE = 'longBayes', q, J)
}

mc_q <- function(mcsamp, J = 6L, burn = 0L) {
    .Call('_longBayes_mc_q', PACKAGE = 'longBayes', mcsamp, J, burn)
}

lspec <- function(mcsamp, J = 6L, burn = 0L) {
    .Call('_longBayes_lspec', PACKAGE = 'longBayes', mcsamp, J, burn)
}

tsl_mc <- function(tsl, J = 6L) {
    .Call('_longBayes_tsl_mc', PACKAGE = 'longBayes', tsl, J)
}

tsl_q <- function(tsl, J = 6L, burn = 0L) {
    .Call('_longBayes_tsl_q', PACKAGE = 'longBayes', tsl, J, burn)
}

lspl <- function(tsl, J = 6L, burn = 0L) {
    .Call('_longBayes_lspl', PACKAGE = 'longBayes', tsl, J, burn)
}

spl <- function(tsl, J = 6L, burn = 0L) {
    .Call('_longBayes_spl', PACKAGE = 'longBayes', tsl, J, burn)
}

